// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_API_KEY_FOR_WEB']}',
    appId: '1:65240847156:web:c3a878107ae95a02db0b61',
    messagingSenderId: '65240847156',
    projectId: 'fruits-hub-d1115',
    authDomain: 'fruits-hub-d1115.firebaseapp.com',
    storageBucket: 'fruits-hub-d1115.firebasestorage.app',
    measurementId: 'G-EZ0DSWKGBM',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_API_KEY_FOR_ANDROID']}',
    appId: '1:65240847156:android:7ff82b0e67f1af6cdb0b61',
    messagingSenderId: '65240847156',
    projectId: 'fruits-hub-d1115',
    storageBucket: 'fruits-hub-d1115.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.env['FIREBASE_API_KEY_FOR_IOS']}',
    appId: '1:65240847156:ios:335b41f2c936eb27db0b61',
    messagingSenderId: '65240847156',
    projectId: 'fruits-hub-d1115',
    storageBucket: 'fruits-hub-d1115.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubApp',
  );
}
